#!/bin/bash

mkdir build
cd build 
rm -f -r *


cmake .. -G "Visual Studio 15 2017 Win64" \
-DURHO3D_CSHARP=OFF \
-DURHO3D_MONOLITHIC_HEADER=ON \
-DURHO3D_SAMPLES=ON \
-DURHO3D_WIN32_CONSOLE=ON \
-DURHO3D_WEBP=OFF \
-DURHO3D_NAVIGATION=OFF \
-URHO3D_URHO2D=OFF \
-DURHO3D_NETWORK=OFF \
-DNEWTON_WITH_AVX2_PLUGIN=ON \
-DNEWTON_DOUBLE_PRECISION=ON
